# Generated by Django 4.0.5 on 2022-06-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_postmedia_postmedium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='postmedium',
            options={'verbose_name_plural': 'post media'},
        ),
        migrations.CreateModel(
            name='SeeAlso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('related_posts', models.ManyToManyField(blank=True, related_name='related_posts', to='posts.post')),
            ],
        ),
    ]
