# Generated by Django 4.0.5 on 2022-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_sociallink_titleelement_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latex',
            field=models.TextField(default='\\documentclass{article}\n%\\documentclass{book}\n\\usepackage[margin=2cm]{geometry}\n\\usepackage{geometry}\n\\usepackage{amsmath}\n\\usepackage{amsthm}\n\\usepackage{amssymb}\n\\usepackage{mathtools}\n\\usepackage{url}\n\\usepackage{cite}\n\\usepackage{caption}\n\\usepackage{subcaption}\n\\usepackage[title]{appendix}\n\\usepackage[colorlinks]{hyperref}\n\\usepackage[capitalize,nameinlink,noabbrev]{cleveref}\n\\usepackage[nottoc,notlot,notlof]{tocbibind}\n\n\n\\title{Default}\n\n\\theoremstyle{definition}\n\n\\newtheorem{definition}{Definition}[section]\n\n\\newtheorem{example}[definition]{Example}\n\\newtheorem{prop}[definition]{Proposition}\n\\newtheorem{lemma}[definition]{Lemma}\n\\newtheorem{thm}[definition]{Theorem}\n\\newtheorem{cor}[definition]{Corollary}\n\\newtheorem{rmk}[definition]{Remark}\n\n\\begin{document}\n\\maketitle\n\\section{Introduction}\n\nThis is the default post\n\n\\end{document}\n'),
        ),
    ]
